# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abom < Formula
  desc "Actions Bill of Materials — map your GitHub Actions supply chain"
  homepage "https://github.com/JulietSecurity/abom"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.2.0/abom_darwin_amd64.tar.gz"
      sha256 "a275f87fd04ddbc93dd52c9b7780908d1028cce25f8ba9b4aa82dcddf8afd7bb"

      define_method(:install) do
        bin.install "abom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.2.0/abom_darwin_arm64.tar.gz"
      sha256 "88774c5321929a03b4daa73ba36666f5ec710079d131699fce9b8eb36c9b5d9b"

      define_method(:install) do
        bin.install "abom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.2.0/abom_linux_amd64.tar.gz"
      sha256 "559c35b59edf59524d2bd27b85d35292ed73c04d4ce3f4e638f4ca3f73ee8c00"
      define_method(:install) do
        bin.install "abom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.2.0/abom_linux_arm64.tar.gz"
      sha256 "0b9f03722bc2a63ea7d1d66967454236e7db569bf64229701f01d2042a103f2c"
      define_method(:install) do
        bin.install "abom"
      end
    end
  end
end
