# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abom < Formula
  desc "Actions Bill of Materials — map your GitHub Actions supply chain"
  homepage "https://github.com/JulietSecurity/abom"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.1.0/abom_darwin_amd64.tar.gz"
      sha256 "968ffebaed162205995ed66ceb9bc6491f6daa8c030d2f522be15a8395c5aa96"

      define_method(:install) do
        bin.install "abom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.1.0/abom_darwin_arm64.tar.gz"
      sha256 "691f40b93b82d2338eae59ec44c8dbe2771f039d5e81d1efd468dda91d1b01fc"

      define_method(:install) do
        bin.install "abom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.1.0/abom_linux_amd64.tar.gz"
      sha256 "8c65daaa7d21889a204825da946fb04e42e6b6be1b5d38f8f7e4b885f378272a"
      define_method(:install) do
        bin.install "abom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.1.0/abom_linux_arm64.tar.gz"
      sha256 "6b59980063ebf9b4481e7c01dee7a5831b67bb0914c405dc63f95dcecbe39128"
      define_method(:install) do
        bin.install "abom"
      end
    end
  end
end
