# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abom < Formula
  desc "Actions Bill of Materials — map your GitHub Actions supply chain"
  homepage "https://github.com/JulietSecurity/abom"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.1.0/abom_darwin_amd64.tar.gz"
      sha256 "233592c76b928440308c0d37909e37adf73d772d321763870e63bbddedb1e333"

      define_method(:install) do
        bin.install "abom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.1.0/abom_darwin_arm64.tar.gz"
      sha256 "3763713a7ca47332c6fddb06575023abc064543b7cffe0e8858566b36f64cea8"

      define_method(:install) do
        bin.install "abom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.1.0/abom_linux_amd64.tar.gz"
      sha256 "308c77e21a9fe6c59e0b0581f1962d52b46babe07d3f91547b9c4e7c25121d2e"
      define_method(:install) do
        bin.install "abom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JulietSecurity/abom/releases/download/v0.1.0/abom_linux_arm64.tar.gz"
      sha256 "449df514ef64b43ca19df320d45ebb9aecd0bee9fbd99fad81fd8abeafa4f643"
      define_method(:install) do
        bin.install "abom"
      end
    end
  end
end
